openapi: 3.0.3

info:
    title: Ping API
    version: 1.0.0

paths:
    /ping:
        post:
            operationId: pingBody
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ping:
                                    type: string
            responses:
                200:
                    description: Returns value of ping
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    pong:
                                        type: string

    /ping/{value}:
        get:
            operationId: ping
            responses:
                200:
                    description: Returns value.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    pong:
                                        type: string
