openapi: 3.0.3

info:
    title: Ping API
    version: 1.0.0

paths:
    /ping:
        post:
            operationId: pingBody
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ping:
                                    type: string
            responses:
                200:
                    description: Returns value of ping
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    pong:
                                        type: string

    /ping/{value}:
        get:
            operationId: ping
            security:
                - Basic: []
            responses:
                200:
                    description: Returns value.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    pong:
                                        type: string
                401:
                    description: Missing Authentication
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"

components:
    securitySchemes:
        Basic:
            type: http
            scheme: basic

    schemas:
        Error:
            type: object
            properties:
                statusCode:
                    type: number
                message:
                    type: string
            required:
                - statusCode
                - message
